name: Build OnePlus SukiSU Ultra
on:
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_MAXSIZE: 8G
      
    steps:
      # ====================== 系统初始化阶段 ======================
      - name: "🚀 Maximize Build Space | 最大化构建空间"
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: "🔐 Configure Git | 配置Git账户"
        run: |
          echo "🔧 正在配置Git用户信息..."
          git config --global user.name "build"
          git config --global user.email "2210077278@qq.com"
          echo "✅ Git配置完成"

      - name: "⬇️ Clone Kernel Source | 克隆内核源码"
        run: |
          echo "🌐 正在初始化内核仓库..."
          mkdir kernel_workspace && cd kernel_workspace
          mkdir kernel_platform && cd kernel_platform
          git clone --depth=1 https://github.com/SunOS-Project/android_kernel_oneplus_sm8750-devicetrees -b bienor sm8750-devicetrees
          git clone --depth=1 https://github.com/SunOS-Project/android_kernel_oneplus_sm8750-modules -b bienor sm8750-modules
          git clone --depth=1 https://github.com/SunOS-Project/android_kernel_oneplus_sm8750 -b bienor common
          mkdir Zyclang20 && cd Zyclang20
          curl -L -O "https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250129-release/Clang-20.0.0git-20250129.tar.gz"
          tar -xzvf Clang-20.0.0git-20250129.tar.gz
          
          cd ..
          sed -i 's/CONFIG_ZRAM=m/CONFIG_ZRAM=y/g' ./common/arch/arm64/configs/gki_defconfig
          rm ./common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          #rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i 's/echo "${KERNELVERSION}${file_localversion}${config_localversion}${LOCALVERSION}${scm_version}"/echo "${KERNELVERSION}${config_localversion}${LOCALVERSION}"/g' ./common/scripts/setlocalversion
          sed -i 's/CONFIG_LOCALVERSION="-4k"/CONFIG_LOCALVERSION="-Kirakira"/g' ./common/arch/arm64/configs/gki_defconfig
          echo "✅ 内核配置完成"     
              
      # ====================== 内核定制阶段 ======================
      - name: "⚡ Setup SukiSU Ultra | 配置SukiSU Ultra"
        run: |
          echo "🛠️ 正在设置SukiSU Ultra..."
          
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          echo "✅ SukiSU Ultra配置完成"
          
      - name: "🔧 Set up SUSFS | 配置 SUSFS"
        run: |
          cd kernel_workspace
          echo "⬇️ 下载SUSFS补丁..."
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6
          git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git 
          
          cd kernel_platform
          echo "📝 复制补丁文件..."
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./common/
          cp ../SukiSU_patch/hooks/scope_min_manual_hooks_v1.5.patch ./common/
          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          
          cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux
          cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib
          cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto
          cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/
          
          
          echo "🔧 应用补丁..."
          cd ./common
          patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true
          cp ../../SukiSU_patch/69_hide_stuff.patch ./
          patch -p1 -F 3 < 69_hide_stuff.patch
          patch -p1 -F 3 < scope_min_manual_hooks_v1.5.patch
        
          echo "🚀 应用lz4kd补丁..."
          cp ../../SukiSU_patch/other/zram/zram_patch/6.6/lz4kd.patch ./
          patch -p1 -F 3 < lz4kd.patch || true
          cp ../../SukiSU_patch/other/zram/zram_patch/6.6/lz4k_oplus.patch ./
          patch -p1 -F 3 < lz4k_oplus.patch || true
          
          echo "✅ 所有补丁应用完成"

      - name: "⚙️ Configure Kernel Options | 配置内核选项"
        run: |
          echo "⚙️ 正在配置内核编译选项..."
          
          cd kernel_workspace/kernel_platform
          
          # Add KSU configuration settings
          echo "📦 启用 Manual Hook..."
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          echo "📦 启用 KPM..."
          echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Add VFS configuration settings
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig    
          
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_ZSMALLOC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_LTO_CLANG_THIN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_LTO=y" >> ./common/arch/arm64/configs/gki_defconfig

          echo "📦 启用lz4kd压缩..."
          echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4K_OPLUS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_ZRAM_WRITEBACK=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          echo "✅ 内核配置更新完成"
          
      - name: "🔨 Build Kernel | 编译内核"
        run: |
          echo "🏗️ 开始内核编译..."
          export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/Zyclang20/bin:$PATH"
          cd kernel_workspace/kernel_platform/common
            
          make clean && make mrproper
          rm -rf out 
          mkdir -p out
            
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="clang" LD=ld.lld HOSTLD=ld.lld O=out gki_defconfig all
          
          echo "✅ 内核编译完成"
                    
      - name: Apply Linux Patch
        run: |
          cd kernel_workspace/kernel_platform/common/out/arch/arm64/boot
          curl -LO https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.12.0/patch_linux
          chmod +x patch_linux
          ./patch_linux
          rm -f Image
          mv oImage Image
         
      - name: Make AnyKernel3
        run: |
          git clone --depth=1 https://github.com/WildKernels/AnyKernel3.git -b gki-2.0      
          rm -rf ./AnyKernel3/.git
          cp kernel_workspace/kernel_platform/common/out/arch/arm64/boot/Image ./AnyKernel3/

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: SukiSU_sunos_oneplus_13
         path: ./AnyKernel3/*
